language: node_js
node_js:
  - "stable"
  
before_script:
  - npm install -g @angular/cli
script:
  - ng build --env=prod /ProjetFrontEnd/
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_DEPLOY
  keep-history: true
  on:
    branch: master